CREATE USER DEMO1 IDENTIFIED BY "Matchalatte@23";
CREATE USER DEMO2 IDENTIFIED BY "MatchaLatte@06";

GRANT CONNECT, RESOURCE TO DEMO1;
GRANT CONNECT, RESOURCE TO DEMO2;

ALTER USER DEMO1 QUOTA 100M ON DATA;
ALTER USER DEMO2 QUOTA 100M ON DATA;
