SELECT dept_name, emp_name, salary, job_title
FROM (
    SELECT 
        d.DNAME AS dept_name,
        e.ENAME AS emp_name,
        e.SAL AS salary,
        e.JOB AS job_title,
        ROW_NUMBER() OVER (
            PARTITION BY e.DEPTNO
            ORDER BY e.SAL ASC, e.EMPNO ASC
        ) AS rn
    FROM EMP e
    JOIN DEPT d ON e.DEPTNO = d.DEPTNO
)
WHERE rn <= 2
ORDER BY dept_name, salary;

SELECT ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC;

SELECT ENAME, JOB, HIREDATE, DEPTNO, SAL
FROM EMP
WHERE TO_CHAR(HIREDATE, 'MM-YYYY') = 
      (SELECT TO_CHAR(HIREDATE, 'MM-YYYY') 
       FROM EMP 
       WHERE ENAME = 'SCOTT');

SELECT e.ENAME, e.JOB, e.SAL, d.DNAME AS DEPT_NAME
FROM EMP e
JOIN DEPT d ON e.DEPTNO = d.DEPTNO
WHERE e.SAL > (
    SELECT AVG(SAL)
    FROM EMP
    WHERE DEPTNO = e.DEPTNO
)
ORDER BY d.DNAME, e.SAL DESC;

SELECT d.DEPTNO, d.DNAME, COUNT(e.EMPNO) AS emp_count
FROM DEPT d
LEFT JOIN EMP e ON d.DEPTNO = e.DEPTNO
GROUP BY d.DEPTNO, d.DNAME
HAVING COUNT(e.EMPNO) = (SELECT MAX(cnt) FROM (SELECT COUNT(*) AS cnt FROM EMP GROUP BY DEPTNO))
   OR COUNT(e.EMPNO) = (SELECT MIN(cnt) FROM (SELECT COUNT(*) AS cnt FROM EMP GROUP BY DEPTNO))
ORDER BY emp_count DESC;

SELECT COLUMN_NAME || ' ' || DATA_TYPE ||
       CASE 
           WHEN DATA_TYPE LIKE '%CHAR%' THEN '(' || DATA_LENGTH || ')' 
           WHEN DATA_TYPE = 'NUMBER' AND DATA_PRECISION IS NOT NULL 
                THEN '(' || DATA_PRECISION || ',' || NVL(DATA_SCALE,0) || ')' 
           ELSE '' 
       END AS column_definition
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'EMP'
ORDER BY COLUMN_ID;


UPDATE EMP
SET HIREDATE = ADD_MONTHS(HIREDATE, (2000 - EXTRACT(YEAR FROM HIREDATE)) * 12)
WHERE EXTRACT(YEAR FROM HIREDATE) = 1981;

COMMIT;


CREATE TABLE EMP_CLONE AS
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE ROWNUM <= 3;  



ALTER SESSION DISABLE PARALLEL DML;

UPDATE EMP_CLONE
SET SAL = SAL * 1.10;  
COMMIT;

UPDATE EMP e
SET e.SAL = (
    SELECT c.SAL
    FROM EMP_CLONE c
    WHERE c.EMPNO = e.EMPNO
)
WHERE EXISTS (
    SELECT 1
    FROM EMP_CLONE c
    WHERE c.EMPNO = e.EMPNO
);

COMMIT;

SELECT EMPNO, ENAME, SAL
FROM EMP
ORDER BY EMPNO;






